### ISSUE TITLE
can't activate twice

### ISSUE THREAD

**Issue by nicolasochem** [oxheadalpha/teztnets#13]
making a release after a testnet already exists causes issues with pulumi: it launches the activate job again, but since the chain is already activated, it fails,and subsequent deployments never run.

A good enough solution is to comment out the `activation` session of every teztnet yaml after it's already activated.

Another solution would be to make tezos-k8s "silently fail" to activate when it's observed that the block number is bigger than 1.

But I'm not too sure about the latter as it's not declarative. Looking for opinions here....

**Comment by nicolasochem** [comment]
Or have release.py dynamically remove activation from the yaml if the teztnet already exists?

**Comment by harryttd** [comment]
A potential option is to use something like Helm hooks https://helm.sh/docs/topics/charts_hooks/
Although it seems pulumi does not work with Helm chart hooks. https://github.com/pulumi/pulumi-kubernetes/issues/555

In the meantime, I think the right thing to do would be having code that comments out the activation section. That way we can still see the values. Ideally the values.yaml on install/upgrade should reflect exactly what is going to deployed.

**Comment by harryttd** [comment]
This may be a way to handle the double activate job:

https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

This can lookup things in an existing cluster. We should be able to conditionally deploy something.
