### ISSUE TITLE
add a mechanism to automatically redeploy some testnets

### ISSUE THREAD

**Issue by nicolasochem** [oxheadalpha/teztnets#8]
Flag testnets are "long-running" or "short running".

For short running testnets, generate a new name and reactivate a new chain from scratch at every release.

**Comment by innov8r** [comment]
Do we really want this for every new release or rather on schedule? I'm thinking each short lifespan testnet might have its own schedule. This would be managed in GitHub CI workflows. When triggered, a new name is generated, set as pulumi parameter (to be picked up in the code) and pulumi up is executed on the same stack as release.

Alternatively, when the scheduled run is initiated, that CI workflow creates a release with the desired updated testnet name and thus (indirectly) causes a pulumi up.

In both cases, new testnet name would result in old testnet (whose name no longer appears in pulumi resource tree) being deprovisioned and new testnet being spun up.

**Comment by nicolasochem** [comment]
On schedule is good. I don't think the github actions should effect the git repo so they should probably not trigger a release, instead they should trigger pulumi up.

One issue with that is that the "latest release notes" stop becoming the source of truth for periodic releases. I suppose the periodic releases should not be part of these release notes and the source of truth for them should be teztnets.xyz
