### ISSUE TITLE
restrict remote signer access

### ISSUE THREAD

**Issue by nicolasochem** [oxheadalpha/teztnets#86]
A regular AWS user (non-root) of the account on which this pulumi deployment is done should not be able to transfer any of the testnets baking account token to a third address, unless they are part of a special IAM group. This unprivileged user still has enough access to do all other devops tasks necessary to maintain the cluster (deploy k8s manifests, run k9s, restart pods, open shell in pods etc)

It means:

* they should not be able to access the baking key directly (k8s secret), otherwise they can just import it to another wallet and transfer the funds out
* they should not be able to open a shell into the remote signer container and read the key (otherwise they can do the above)
* they should not be able to sign a transfer operation using the remote signer http interface (signing a bake/endorse operation would be ok, though). The remote signer can be launched with special arguments that allow this (this would require tezos-k8s patch)
* maybe other attack vectors exist

This requires mapping IAM permissions to role-based access control of k9s.

All of this should be pulumized. So hypothetically, we would be able to destroy and recreate the entire infrastructure, and this unprivileged user would still not be able to do any of the above.

**Comment by harryttd** [comment]
Also should not be able to create roles/policies that would give them the access. 

Please see https://docs.google.com/document/d/1oncRINCTlh80hRyvJ1gj0HIWuxtoRu6C5Sb8MeRHW9Q/edit#bookmark=id.vnb421cjuetw for more details on potential attack vectors and necessary steps we should take to secure our infra.
